import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import "./globals.css";
import AppProvider from "@/provider/AppProvider";
import AuthProvider from "@/provider/AuthProvider";
import { Toaster } from "sonner";
import NextTopLoader from 'nextjs-toploader'
import SmoothScrollProvider from "@/provider/SmoothScrollProvider";

const manrope = Manrope({
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700", "800"],
  variable: "--font-manrope",
});

export const metadata: Metadata = {
  title: "Modern Med Centers",
  description: "Generated by create renram",
  icons: {
    icon: "/fav.png",
  }
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${manrope.variable} font-sans antialiased`}>
        <NextTopLoader color="#0024DA" height={3} showSpinner={false} />
        <AppProvider>
          <SmoothScrollProvider>
          <AuthProvider>{children}</AuthProvider>
          </SmoothScrollProvider>
          <Toaster richColors position="top-right" />
        </AppProvider>
      </body>
    </html>
  );
}
